# Generated by Django 5.2.6 on 2025-12-23 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_alter_cart_options_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='statuses',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='deliveryslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryslot',
            name='slot_type',
            field=models.CharField(choices=[('morning', 'Morning (9 AM - 12 PM)'), ('evening', 'Evening (5 PM - 8 PM)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='current_status',
            field=models.CharField(choices=[('placed', 'Placed'), ('packed', 'Packed'), ('out_for_delivery', 'Out for delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='placed', max_length=20),
        ),
        migrations.DeleteModel(
            name='OrderStatus',
        ),
    ]
