# Generated by Django 5.2.6 on 2025-12-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0012_alter_category_options_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment'), ('COD', 'Cash on Delivery')], default='ONLINE', max_length=20),
        ),
    ]
